### ISSUE TITLE
Write the Doc 

### ISSUE THREAD

**Issue by ksheetal** [Skill-Class/First-Contribution#2]
Can you please write the doc for people who are doing contribution for the first time?
For Ref, you check this - [https://github.com/diamondlee7/first-contributions/blob/master/README.md](URL)

**Comment by IMPrimph** [comment]
@ksheetal 
I am interested to write
Can you assign me this?

**Comment by ksheetal** [comment]
Hey @IMPrimph 
Thanks for taking interest in issue #1 
I am assigning it to you.!
All the very best :)

**Comment by IMPrimph** [comment]
Shall I do it on the readme file, or else you want me to add a separate file?

**Comment by ksheetal** [comment]
Dear @IMPrimph 
Please follow the steps mentioned below -
1. Fork the repo.
2. Create your separate branch as "readme-IMPrimph"
3. Update Readme Doc.
4. Commit your changes and push to your repo.
5. Create a pull request.

These are the basic steps.
hope it helps.

Thanks.

**Comment by IMPrimph** [comment]
Ok, got it!

**Comment by IMPrimph** [comment]
Done!

**Comment by ksheetal** [comment]
Hi @IMPrimph, I am not about to see your pull. Please create one.

Thanks.

**Comment by IMPrimph** [comment]
https://github.com/IMPrimph/First-Contribution/pull/1

**Comment by IMPrimph** [comment]
https://github.com/IMPrimph/First-Contribution/pull/1

**Comment by IMPrimph** [comment]
I have already created
Check this
